service: note-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: shortlinker_v2
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource:
        - Fn::GetAtt: [ NotesTable, Arn ]
        - Fn::GetAtt: [ LinksTable, Arn ]
        - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.linksTableName}/index/ShortUrlIndex'

    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:us-east-1:870642761716:function:note-app-dev-deleteNote"
    - Effect: "Allow"
      Action:
        - "iam:PassRole"
      Resource: "arn:aws:iam::870642761716:role/RemoveLambdaRole"
    - Effect: "Allow"
      Action:
        - "scheduler:CreateSchedule"
      Resource: "*"
  environment:
    NOTES_TABLE: ${self:custom.notesTableName}
    LINKS_TABLE: ${self:custom.linksTableName}

functions:
  createNote:
    handler: src/lambdas/createNote.handler
    events:
      - http:
          path: notes
          method: post
          cors: true
  deleteNote:
    handler: src/lambdas/deleteNote.handler
    events:
      - http:
          path: notes/{noteId}
          method: delete
          cors: true
  createSchedule:
    handler: src/lambdas/createSchedule.handler
    events:
      - http:
          path: schedule
          method: post
          cors: true
  createLink:
    handler: src/lambdas/createLink.handler
    events:
      - http:
          path: links
          method: post
          cors: true
  linkDeactivation:
    handler: src/lambdas/linkDeactivation.handler
  getLinkFromShortUrl:
    handler: src/lambdas/getLinkFromShortUrl.handler
    events:
      - http:
          path: /{linkId}
          method: get

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.notesTableName}
        AttributeDefinitions:
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: noteId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    LinksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.linksTableName}
        AttributeDefinitions:
          - AttributeName: linkId
            AttributeType: S
          - AttributeName: shortUrl
            AttributeType: S
        KeySchema:
          - AttributeName: linkId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ShortUrlIndex
            KeySchema:
              - AttributeName: shortUrl
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"

    RemoveLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: RemoveLambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
                  - "events.amazonaws.com"
                  - "scheduler.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: LambdaSchedulerFunction
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - "scheduler:CreateSchedule"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "lambda:InvokeFunction"
                  Resource:
                  - "arn:aws:lambda:us-east-1:870642761716:function:note-app-dev-deleteNote:*"
                  - "arn:aws:lambda:us-east-1:870642761716:function:note-app-dev-deleteNote"
                  - "arn:aws:lambda:us-east-1:870642761716:function:note-app-dev-linkDeactivation:*"
                  - "arn:aws:lambda:us-east-1:870642761716:function:note-app-dev-linkDeactivation"

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: [ 'aws-sdk' ]
    target: 'node18'
    define: { 'require.resolve': undefined }
    platform: 'node'
  notesTableName: NotesTable
  linksTableName: ShortLinksTable
